Service = "sif-json2xml"
Version = "v0.1.5"

[SIF]
  DefaultVer = "3.4.7"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1325

[Route]
  Convert = "/sif-json2xml/convert"
  Help = "/"

[NATS]
  Timeout = 500
  URL = "nats://192.168.78.130:4222"
  Subject = "SIF-JSON2XML"

