Log = "~/.[s]/log/[DATE].log"
Service = "[PRJ]"
Version = "[VER]"

[SIF]
DefaultVer = "3.4.7"

[Loggly]
Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
Port = 1325

[Route]
Convert = "/[s]/[v]/convert"
Help = "/"

[NATS]
Subject = "SIF-JSON2XML"
Timeout = 500
URL = "nats://192.168.78.130:4222"

[Server]
IP = "[IP]"
Port = "[port]"
Protocol = "http"

[Access]
Timeout = 10
